In [6]:
import pandas as pd 
import numpy as np


df = pd.read_csv("investment_recommendations_10000.csv")

In [9]:
data_shape = df.shape
data_shape

(10000, 6)

In [7]:
data_info = df.info()
data_info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Individual Goals                 10000 non-null  object
 1   Age                              10000 non-null  int64
 2   Gender                           10000 non-null  object
 3   Risk Tolerance                   10000 non-null  object
 4   Financial Literacy               10000 non-null  int64
 5   Recommended Investment Products  10000 non-null  object
dtypes: int64(2), object(4)
memory usage: 468.9+ KB

In [8]:
data_description= df.describe()
data_description

               Age  Financial Literacy
count  10000.00000        10000.000000
mean      39.84960            3.025500
std       23.27352            1.413807
min        0.00000            1.000000
25%       20.00000            2.000000
50%       40.00000            3.000000
75%       60.00000            4.000000
max       80.00000            5.000000

In [10]:
has_nulls = df.isnull().values.any()
has_nulls

False

In [11]:
column_names = df.columns
column_names

Index(['Individual Goals', 'Age', 'Gender', 'Risk Tolerance',
       'Financial Literacy', 'Recommended Investment Products'],
      dtype='object')

In [23]:
head = df.head()
head

,Individual Goals,Age,Gender,Risk Tolerance,Financial Literacy,Recommended Investment Products
0,saving for retirement,44,Male,Medium,2,"Mutual Funds, PPF, NPS, Stocks, Real Estate"
1,buying a house,47,Male,Medium,2,"Real Estate Investment Trusts (REITs), Home Lo..."
2,saving for education,64,Male,Low,4,"National Scholarship Scheme, Education Bonds, ..."
3,saving for retirement,67,Female,High,2,"Mutual Funds, PPF, NPS, Stocks, Real Estate"
4,saving for education,67,Male,High,3,"National Scholarship Scheme, Education Bonds, ..."

In [22]:
unique_element_count={}
unique_element={}
for column in column_names:
    count = df[column].nunique()
    unique_element_count[column] = (count)
    unique_elements = (count, df[column].unique())
unique_element_count, unique_elements

({'Individual Goals': 6,
  'Age': 81,
  'Gender': 2,
  'Risk Tolerance': 3,
  'Financial Literacy': 5,
  'Recommended Investment Products': 18},
 (18,
  array(['Mutual Funds, PPF, NPS, Stocks, Real Estate',
         'Real Estate Investment Trusts (REITs), Home Loans, Stocks, Real Estate',
         'National Scholarship Scheme, Education Bonds, Education Loans, Stocks, Mutual Funds',
         "Sukanya Samriddhi Yojana, Children's Mutual Funds, Real Estate Investment Trusts (REITs), Home Loans, Stocks",
         "Children's Mutual Funds, Personal Loans, Consumer Stocks, Gold, Mutual Funds",
         'Personal Loans, Consumer Stocks, Gold, Mutual Funds, Cryptocurrency',
         'Stand-Up India Scheme, Equity Shares, Business Loans, Stocks, Real Estate',
         "Children's Mutual Funds, National Scholarship Scheme, Education Bonds, Education Loans, Stocks",
         'Travel Insurance, Short-Term Mutual Funds, Savings Account, Stocks, Cryptocurrency',
         "Sukanya Samriddhi Yojana, Children's Mutual Funds, National Scholarship Scheme, Education Bonds, Education Loans",
         "Children's Mutual Funds, Stand-Up India Scheme, Equity Shares, Business Loans, Stocks",
         "Children's Mutual Funds, Real Estate Investment Trusts (REITs), Home Loans, Stocks, Real Estate",
         "Sukanya Samriddhi Yojana, Children's Mutual Funds, Personal Loans, Consumer Stocks, Gold",
         "Children's Mutual Funds, Travel Insurance, Short-Term Mutual Funds, Savings Account, Stocks",
         "Children's Mutual Funds, Mutual Funds, PPF, NPS, Stocks",
         "Sukanya Samriddhi Yojana, Children's Mutual Funds, Mutual Funds, PPF, NPS",
         "Sukanya Samriddhi Yojana, Children's Mutual Funds, Travel Insurance, Short-Term Mutual Funds, Savings Account",
         "Sukanya Samriddhi Yojana, Children's Mutual Funds, Stand-Up India Scheme, Equity Shares, Business Loans"],
        dtype=object)))